WITH 
SERVER_DATA AS (
SELECT
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ROWNUM" AS "ROWNUM",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."TIMESTAMP_" AS "TIMESTAMP_",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ART_DAILY_FLATMIDDLE" AS "ART_DAILY_FLATMIDDLE",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ART_DAILY_JUMPSDOWN" AS "ART_DAILY_JUMPSDOWN",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ART_DAILY_JUMPSUP" AS "ART_DAILY_JUMPSUP",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ART_LOAD_BALANCER_SPIKES" AS "ART_LOAD_BALANCER_SPIKES",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ART_INCREASE_SPIKE_DENSITY" AS "ART_INCREASE_SPIKE_DENSITY",
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"."ART_DAILY_NOJUMP" AS "ART_DAILY_NOJUMP"
FROM
  "snowflake"."SCHEMA_INFO"."ARTIFICIALWITHANOMALYFOUR"
LIMIT
  100
)
SELECT SERVER_DATA.TIMESTAMP_ as TIME_STAMP, SERVER_DATA."ART_LOAD_BALANCER_SPIKES" AS "LOAD BALANCER SPIKES",  SERVER_DATA."ART_INCREASE_SPIKE_DENSITY" AS "INCREASE IN SPIKE DENSITY"
FROM SERVER_DATA
WHERE SERVER_DATA.TIME_STAMP IS NOT NULL
